spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taotao?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    cache: false
#    mode: HTML5
    mode: LEGACYHTML5
    servlet:
      content-type: text/html


server:
  port: 8081

#application:
#  name: taotao-dubbo-consumer
dubbo:
  application:
    name: taotao-dubbo-consumer   #别名，消费方应用信息，不要与提供方相同
  registry:
    address: zookeeper://192.168.31.74:2181 #注册中心地址，调用服务

  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.taotao.controller


TAOTAO_IMAGE_SERVER_URL: http://192.168.31.74/